### ISSUE TITLE
Feature request: Expose memoize_ttl() as function decorator too

### ISSUE THREAD

**Issue by JohanLorenzo** [michalc/aiomemoizettl#2]
Hi @michalc! 

First of all, thank you very much for creating this library 😃

I was told about it about [a week ago](https://bugzilla.mozilla.org/show_bug.cgi?id=1596439#c1) and I was so relieved because it solves a problem Mozilla has had a few times [over the past months](https://github.com/mozilla-releng/scriptworker/pull/332). I'm really happy to open the very first issue 🙂

While working on https://github.com/mozilla-releng/scriptworker/pull/411, I realized it would make the code cleaner if `memoize_ttl()` was also a function decorator. For instance:

```py
async def _do_some_async_stufff(*args, **kwargs):
    # process data
    return await do_stuff(*args, **kwargs)

_memoized_do_some_async_stuff = memoize_ttl(
    _do_some_async_stufff, get_ttl=lambda _: 10*60  # 10 minutes
)

async def async_main():
    value = _memoized_do_some_async_stuff()
    # process data
```

could become: 

```py
@memoize_ttl(get_ttl=lambda _: 10*60  # 10 minutes)
async def _do_some_async_stuff(*args, **kwargs):
    # process data
    return await do_stuff(*args, **kwargs)

async def async_main():
    value = _do_some_async_stuff()
    # process data
```

What do you think?

**Comment by michalc** [comment]
Hello!

> First of all, thank you very much for creating this library

No problem: I'm pleased you like it :-)

> What do you think?

I'm a bit anti for this to be in the library to be honest. I'm quite a fan of the extremely simple/small API, with only a single way of achieving the memoization. I also tend to avoid decorators, especially if they introduce what is equivalent to global state(?), so it's not a code path that I will be using myself, so it would essentially be (a tiny bit) more dead code in my projects that use this library, were I to update to the latest version.

However, you can implement a decorator yourself

```python
def memoize_ttl_decorator(get_ttl):
    def _memoized(coro):
        return memoize_ttl(coro, get_ttl)
    return _memoized
```

or even, if using `functools.partial`, it's even less code

```python
def memoize_ttl_decorator(get_ttl):
    return functools.partial(memoize_ttl, get_ttl=get_ttl)
```

Note also, this library is very small: you can fork it and change it as you see fit, or even introduce it into your codebase and change it there (subject to licenses etc). There is particular behaviour with exceptions and when the TTL starts that may or may not fit your use case, so you may like to change that etc.

**Comment by JohanLorenzo** [comment]
Hi!

Thank you very much for your quick and detailed answer! I understand your point of view and I agree, it does create a global state. I'll get the decorator implemented in my code base 🙂 Thanks for the help!
